### PR TITLE
Unique name for auth file

### LINKED ISSUE #30: Race condition with static auth.json filename
https://github.com/eth-cscs/sarus/blob/75e223bfe555c15f41d6394b41750c74d56e1d98/src/image_manager/SkopeoDriver.cpp#L233

The filename for pulling an image from a registry which requires authentication has a race condition. Consider the following workflow:
- Pull1 starting for my.registry.com/container_image_1:latest
- Pull2 starting for my.registry.com/container_image_2:lastest
- Pull1 writing authentication information to auth.json for my.registry.com/container_image_1
- Pull2 writing authentication information to auth.json for my.registry.com/container_image_2
- Pull1 reaching the point where it wants to actually do `skopeo copy --src-authfile auth.json`
- Pull2 reaching the point where it wants to actually do `skopeo copy --src-authfile auth.json`

At this point Pull2 would be successful, because the authentication for Pull2 is in auth.json, but Pull1 will fail, because the authentication information for Pull1 was overwritten by Pull2

An obvious way to fix this is to have a unique name for the authentication file.

### PR DESCRIPTION
**Pull request by finkandreas**
This should fix #30

### CODE REVIEW

**Comment by Madeeks** [comment]
Thanks for opening this!
A few kind requests and suggestions:
- Could you please rebase this branch on `develop` and also target the PR to `develop`?
- Would you be willing to update the [unit tests regarding the auth file](https://github.com/eth-cscs/sarus/blob/develop/src/image_manager/test/test_SkopeoDriver.cpp#L216)?
- The utility function [makeUniquePathWithRandomSuffix()](https://github.com/eth-cscs/sarus/blob/develop/src/common/Utility.cpp#L434) is a more fitting choice for this fix, and internally calls `generateRandomString()` which you already used in the commit.
- I believe this deserves a mention as a `Fixed` item in the changelog. I can take care of that if you prefer.

**Comment by finkandreas** [comment]
- I have changed the base to `develop`
- adapted the unit tests
  - The first check for non-existent `auth.json` seems a little bit unnecessary, but I left it there
- I did not spot the functio n`makeUniquePathWithRandomSuffix()`, but you are absolutely right, it is the better choice
- I added a changelog item, feel free to change the wording there

File: src/image_manager/SkopeoDriver.cpp [hunk 1]
```diff
@@ -230,11 +230,12 @@ void SkopeoDriver::acquireAuthFile(const common::Config::Authentication& auth, c
     rapidjson::Pointer(jsonPointer.str().c_str()).Set(authJSON, encodedCredentials.c_str());
 
     common::createFoldersIfNecessary(authFileBasePath);
-    authFilePath = authFileBasePath / "auth.json";
+    authFilePath = common::makeUniquePathWithRandomSuffix(authFileBasePath / "auth.json");
```
Comment (Madeeks) [inline src/image_manager/SkopeoDriver.cpp:233]: Given the way `makeUniquePathWithRandomSuffix()` works, the auth file path would result in `<base path>/auth.json-<random string>`.

Do you think something like
`common::makeUniquePathWithRandomSuffix(authFileBasePath / "sarus-auth").replace_extension(.json);`
would be more elegant?

This is a pure formality, since the code would work anyways (considering the path is passed explicitly to Skopeo).

File: src/image_manager/test/test_SkopeoDriver.cpp [hunk 2]
```diff
@@ -242,7 +242,9 @@ TEST(SkopeoDriverTestGroup, acquireAuthFile) {
             CHECK_FALSE(boost::filesystem::exists(expectedAuthFilePath));
```
Comment (Madeeks) [inline src/image_manager/test/test_SkopeoDriver.cpp:242]: With the auth file moving to a random path, it makes little sense to check whether a hardcoded path exists or not. I agree this is unnecessary and can be removed.

File: src/image_manager/test/test_SkopeoDriver.cpp [hunk 3]
```diff
@@ -242,7 +242,9 @@ TEST(SkopeoDriverTestGroup, acquireAuthFile) {
...
 
             auto driver = image_manager::SkopeoDriver{config};
-            driver.acquireAuthFile(config->authentication, config->imageReference);
+            auto randomExpectedAuthFilePath = driver.acquireAuthFile(config->authentication, config->imageReference);
+            CHECK_TRUE(expectedAuthFilePath != randomExpectedAuthFilePath);
```
Comment (Madeeks) [inline src/image_manager/test/test_SkopeoDriver.cpp:246]: Writing  here but the following comments apply to all  cases under this test.

I think the check and reassignment between `expectedAuthFilePath`  and `randomExpectedAuthFilePath` is not necessary and can be simplified to a direct assignment to `authFilePath`.

On the other hand, I suggest to check that the auth file is created in the expected directories (in the case of this code scope, the XDG Runtime Dir). For example, something like:
```
CHECK(authFilePath.parent_path() == (xdgRuntimeDir / "sarus"))
```

**Review by Madeeks — CHANGES_REQUESTED** [review]

File: src/image_manager/test/test_SkopeoDriver.cpp (hunk 3 above)
Comment (finkandreas) [reply src/image_manager/test/test_SkopeoDriver.cpp]: Done - I think I kept the check that the filename is unique, to make sure that I really do not use the old implementation. Anyway I removed it now, since I'm almost certain that it does not create the old static filename.

**Review by Madeeks — APPROVED** [review]
LGTM!
